name: floo_network_web
description: "Floo Network Web."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  http: ^1.2.1
  uuid: ^4.4.0
  web: ^0.5.1
  web_socket_channel: ^3.0.0
  x_responsive: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
